{% set name = "goulib" %}
{% set version = "1.9.22" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d801762ae9eb05c70eed8a982b3c800fd6eca033adcae9f3f8e7b5af4b5d644f" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - scipy
    - matplotlib
    - networkx
    - pydot
    - pydotplus
    - graphviz
    - six
    - ipython
    - lxml
    - xlrd
    - xlsxwriter
    - pillow
    - scikit-image
    - dxfgrabber
    - dxfwrite
    - svg.path
    - pdfminer.six
    - sortedcontainers
    - pint
    - nose
    - sphinx >=1.4.2
  run:
    - python
    - scipy
    - matplotlib
    - networkx
    - pydot
    - pydotplus
    - graphviz
    - six
    - ipython
    - lxml
    - xlrd
    - xlsxwriter
    - pillow
    - scikit-image
    - dxfgrabber
    - dxfwrite
    - svg.path
    - pdfminer.six
    - sortedcontainers
    - pint
    - nose
    - sphinx >=1.4.2

test:
  imports:
    - Goulib

about:
  home: http://github.com/goulu/goulib
  license: GNU Library or Lesser General Public License (LGPL)
  license_family: LGPL
  license_file: ''
  summary: library of useful Python code for scientific + technical applications
  description: "Goulib\n======\n\nlibrary of useful Python code for scientific + technical applications\n\nsee the `IPython notebook <http://nbviewer.ipython.org/github/Goulu/Goulib/blob/master/notebook.ipynb>`_\
    \ for an overview of features\n\n.. image:: http://img.shields.io/badge/license-LGPL-green.svg\n    :target: https://github.com/goulu/Goulib/blob/master/LICENSE.TXT\n    :alt: License\n.. image:: https://badge.fury.io/py/goulib.svg\n\
    \    :target: https://pypi.python.org/pypi/Goulib/\n    :alt: Version\n.. image:: https://travis-ci.org/goulu/Goulib.svg?branch=master\n    :target: https://travis-ci.org/goulu/Goulib\n    :alt: Build\n\
    .. image:: https://coveralls.io/repos/github/goulu/Goulib/badge.svg?branch=master\n    :target: https://coveralls.io/github/goulu/Goulib?branch=master\n    :alt: Tests\n.. image:: https://readthedocs.org/projects/goulib/badge/?version=latest\n\
    \  :target: http://goulib.readthedocs.org/en/latest/\n  :alt: Doc\n.. image:: https://www.openhub.net/accounts/Goulu/widgets/account_tiny?format=gif\n    :target: https://www.openhub.net/accounts/Goulu\n\
    .. image:: https://api.coderwall.com/goulu/endorsecount.png\n    :target: https://coderwall.com/goulu\n  \n:author: Philippe Guglielmetti goulib@goulu.net\n:installation: \"pip install Goulib\"\n:distribution:\
    \ https://pypi.python.org/pypi/Goulib\n:documentation: https://goulib.readthedocs.org/\n:notebook: http://nbviewer.ipython.org/github/Goulu/Goulib/blob/master/notebook.ipynb\n:source: https://github.com/goulu/Goulib\n\
    \nModules\n-------\n\n**colors**\n\tvery simple RGB color management\n**container**\n    sorted collection\n**datetime2**\n\tadditions to datetime standard library\n**decorators**\n\tuseful decorators\n\
    **drawing**\n\tRead/Write and handle vector graphics in .dxf, .svg and .pdf formats\n**expr**\n\tsimple symbolic math expressions\n**geom**, **geom3d**\n\t2D + 3D geometry\n**graph**\n\tefficient Euclidian\
    \ Graphs for `NetworkX <http://networkx.github.io/>`_ and related algorithms\n**image**\n    image processing and conversion\n**interval**\n\toperations on [x..y[ intervals\n**itertools2**\n\tadditions\
    \ to itertools standard library\n**markup**\n\tsimple HTML/XML generation (forked from `markup <http://pypi.python.org/pypi/markup/>`_)\n**math2**\n\tadditions to math standard library\n**motion**\n\
    \tmotion simulation (kinematics)\n**optim**\n\toptimization algorithms : knapsack, traveling salesman, simulated annealing\n**piecewise**\n\tpiecewise-defined functions\n**plot**\n    plotable rich\
    \ object display on IPython notebooks\n**polynomial**\n\tmanipulation of polynomials\n**statemachine**\n    state machines with graph representation\n**stats**\n    very basic statistics functions\n\
    **table**\n\tTable class with Excel + CSV I/O, easy access to columns, HTML output, and much more.\n**tests**\n    utilities for unit tests (using nose)\n**workdays**\n\tWorkCalendar class with datetime\
    \ operations on working hours, handling holidays\n\tmerges and improves `BusinessHours <http://pypi.python.org/pypi/BusinessHours/>`_ and `workdays <http://pypi.python.org/pypi/workdays/>`_ packages\n\
    \nRequirements\n------------\n\nGoulib uses lazy requirements.\nMany modules and functions do not require any other packages,\npackages listed in requirements.txt are needed only by some Goulib classes\
    \ or functions"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
