from __future__ import division #"true division" everywhere

"""
Friedman numbers and related
"""

__author__ = "Philippe Guglielmetti"
__copyright__ = "Copyright (c) 2017 Philippe Guglielmetti"
__license__ = "LGPL"
__credits__ = ["https://en.wikipedia.org/wiki/Friedman_number"]

__docformat__ = 'restructuredtext'
__version__ = '$Id$'
__revision__ = '$Revision$'

import six
import logging
from itertools import permutations, product, count
import math
from Goulib import math2, itertools2
from Goulib.expr import Expr
from sortedcontainers import SortedDict

class Results(SortedDict):
    """ Expr indexed by their result """

    def __init__(self, int=False, min=0, max=None, improve=True):
        super(Results,self).__init__()
        self.int=int # if only ints should be stored
        self.min=min
        self.max=max
        self.improve = improve # whether insert should replace complex formula by simpler

    def add(self,expr):
        if expr is None:
            return
        k=expr() # the key is the numeric value of expr
        
        if k is None: 
            return # NaN such as /0

        if self.int:
            if type(k) is complex or not math2.is_integer(k):
                return
            k=math2.rint(k)

        if self.min is not None and k<self.min :
            return

        if self.max is not None and k>self.max :
            return

        if k in self:
            if self.improve and expr.complexity() < self[k].complexity():
                pass
            else:
                return
        
        self[k]=expr



# supported operators with precedence and text + LaTeX repr
# precedence as in https://docs.python.org/2/reference/expressions.html#operator-precedence
#

def concat(left,right):
    if left.isNum and right.isNum and left>0 and right>=0:
        return Expr(str(left)+str(right))
    else:
        return None

def _diadic(left,op,right):
    if op=='+': return left+right
    if op=='-': return left-right
    if op=='*': return left*right
    if op=='/': return left/right
    if op=='^':
        return left**right
    if op=='**': return left**right
    if op=='_':
        return concat(left,right)

def _monadic(op,e):
    if op=='': return e
    if op=='-': return -e
    if op=='s': return Expr(math.sqrt)(e)

def gen(digits,monadic='-', diadic='-+*/^_',permut=True):
    """
    generate all possible Expr using digits and specified operators
    """
    if isinstance(digits,six.integer_types):
        digits=str(digits)
    if isinstance(digits,six.string_types):
        digits=list(digits)
    if permut:
        for d in permutations(digits):
            for x in gen(d,monadic, diadic,False):
                yield x
        return

    if len(digits)==1 or '_' in diadic:
        try:
            e=Expr(''.join(digits))
            if e.isNum:
                yield e
                for op in monadic:
                    yield _monadic(op,e)
        except:
            pass

    for i in range(1,len(digits)):
        try:
            for x in product(
                gen(digits[:i], monadic, diadic, permut),
                diadic,
                gen(digits[i:], monadic, diadic, permut),
            ):
                yield _diadic(*x)
        except:
            pass


def seq(digits,monadic,diadic,permut):
    """
    returns a sequence of Expr generated by gen(**kwargs)
    which evaluate to 0,1,...
    """

    b=Results(int=True)
    i=0
    for e in gen(digits,monadic, diadic, permut):
        b.min=i
        b.add(e)
        while i in b:
            yield (i,b.pop(i))
            i+=1
    for k in b:
        yield (k,b[k])

def pp(e):
    """ pretty print, clean the formula (should be dont in Expr...="""
    f=str(e[1])
    # f=f.replace('--','+')
    # f=f.replace('+-','-')
    print('%d = %s'%(e[0],f))

def yeargame(num):
    return seq(num,'-s','+-*/_',True)

def fourfour():
    return seq(4444,'-s','+-*/_',False)

def friedman(num):
    for e in gen(num):
        try:
            n=math2.int_or_float(e()) #cope with potential rounding problems
            if n==num and str(e)!=str(num): #concat is too easy ...
                yield (num,e)
        except GeneratorExit: # https://stackoverflow.com/a/41115661/1395973
            return
        except:
            pass


if __name__ == "__main__":


    print('\n4444')
    for e in fourfour():
        pp(e)


    print('\nyeargame')
    for e in yeargame(2017):
        pp(e)


    print('\nfriedman')
    for x in count(10):
        try:
            e=itertools2.first(friedman(x))
            pp(e)
        except IndexError: # no solution found
            pass




