name: "Generate Sphinx Documentation"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2
    - name: Install Shpinx
      run: |
        python -m pip install --upgrade pip
        python -m pip install sphinx sphinx_rtd_theme
    - name: Build HTML
      run: | 
        cd docs/
        make html
    - name: Run ghp-import
      run: | 
        ghp-import -n -p -f docs/build/html